######################################################################
# Automatically generated by qmake (3.1) Tue Sep 9 14:26:07 2025
######################################################################

TEMPLATE = app
TARGET = Tenco
INCLUDEPATH += .
DESTDIR     = $$PWD/../bin
CONFIG      += warn_on
greaterThan(QT_MAJOR_VERSION, 5): QT += core5compat
# Qt modules
QT += core gui widgets
QT += network
QT += websockets


# C++ standard
CONFIG += c++17

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += mainwindow.h \
           battery.h \
           imageswitch.h \
           home.h \
           map.h \
           maintenance.h \
           help.h \
           about.h \
           homenetworkworker.h \
           mapgraphicsview.h \
           statusclient.h \
           chassisclient.h \
           videoclient.h \
           routefollower.h \
           configmanager.h

FORMS += mainwindow.ui

SOURCES += main.cpp \
           UI_Design.cpp \
           mainwindow.cpp \
           battery.cpp \
           imageswitch.cpp \
           home.cpp \
           map.cpp \
           maintenance.cpp \
           help.cpp \
           about.cpp \
           homenetworkworker.cpp \
           mapgraphicsview.cpp \
           statusclient.cpp \
           chassisclient.cpp \
           videoclient.cpp \
           routefollower.cpp \
           configmanager.cpp

RESOURCES += resources.qrc

RC_FILE +=app_icon.rc




